import type { Locale } from '../i18n/config';

export const ui: Record<Locale, { live: string; soon: string; code: string; back: string; visit: string; charts: Record<string, string> }> = {
  fr: {
    live: 'En ligne',
    soon: 'Bientôt',
    code: 'Code',
    back: 'Retour au portfolio',
    visit: 'Visiter le dashboard',
    charts: {
      probability: 'Probabilité de qualification',
      points: 'Points obtenus',
      after: 'Après',
      missed: 'occasion manquée',
      scored: 'occasion convertie',
      concedeRate: 'Taux d\'encaissement suivant',
      competition: 'Compétition',
      effect: 'Effet estimé (points de %)',
      metric: 'Indicateur',
      goldenAge: 'Âge d\'or (2008-2012)',
      crisisAge: 'Ère actuelle (2023-2025)',
      table: 'Voir les données en tableau',
      hideTable: 'Masquer le tableau',
    },
  },
  en: {
    live: 'Live',
    soon: 'Coming soon',
    code: 'Code',
    back: 'Back to portfolio',
    visit: 'Visit the dashboard',
    charts: {
      probability: 'Qualification probability',
      points: 'Points earned',
      after: 'After a',
      missed: 'missed chance',
      scored: 'converted chance',
      concedeRate: 'Following concede rate',
      competition: 'Competition',
      effect: 'Estimated effect (pp)',
      metric: 'Metric',
      goldenAge: 'Golden Age (2008-2012)',
      crisisAge: 'Current Era (2023-2025)',
      table: 'View data as a table',
      hideTable: 'Hide table',
    },
  },
};
